FROM golang:1.23.1-bullseye AS base-i386-linux

LABEL os=linux
LABEL arch=i386

RUN apt-get update \
  && apt-get install -y --no-install-recommends \
  pkg-config:i386 \
  portaudio19-dev:i386

RUN apt-get update \
  && apt-get install -y --no-install-recommends \
  xcb:i386 \
  libxcb-xkb-dev:i386 \
  x11-xkb-utils:i386 \
  libx11-xcb-dev:i386 \
  libxkbcommon-x11-dev:i386 \
  libxkbcommon-dev:i386 \
  gcc:i386 libc6-dev:i386 \
  libx11-dev:i386 xorg-dev:i386 libxtst-dev:i386 \
  xsel:i386 xclip:i386 \
  libpng++-dev:i386 && \
  apt-get clean

FROM base-i386-linux AS builder-i386-linux

ENV GOOS=linux
ENV GOARCH=386
ENV CGO_ENABLED=1
ENV CC=gcc

WORKDIR /app

# Copy go.mod and go.sum
COPY go.mod go.sum ./

# Download dependencies
RUN go mod download

# Copy source code
COPY . .

RUN go build \
  -ldflags "-X main.buildDate=${BUILD_DATE} -X main.buildVersion=${BUILD_VERSION}" \
  -o nomi-cli ./cmd/cli

# Final stage
FROM alpine:latest

# Install runtime dependencies
RUN apk add --no-cache libstdc++ portaudio

# Set work directory
WORKDIR /app

ARG TARGETOS
ARG TARGETARCH

# Copy binary from builder
COPY --from=builder-i386-linux /app/nomi-cli /app/nomi-cli

# Entry point
CMD ["./nomi-cli"]